### ISSUE TITLE
Possible CSS minor issues

### ISSUE THREAD

**Issue by ezehnder** [creativetimofficial/ct-now-ui-dashboard-pro#45]
Hi, 

I found a few issues with CSS, I'm not sure if those are bugs or intentionally made by design, please find the details below:

1. .btn-sm has a font size bigger than the regular and large buttons, I would expect the font size to be the same or maybe smaller, but not bigger.

2. When using .btn-sm in combination with .btn-round, the button remains big (its dimensions do not get smaller)

3. When navigating some pages on mobile (eg. Register and Login page), I can see a menu button that does nothing. It is hidden on desktop, maybe it should be hidden on mobile as well?
![image](https://user-images.githubusercontent.com/33011219/45100217-71f79480-b0ff-11e8-87df-ade7c94f7e71.png)

Thank you.

**Comment by dragosct** [comment]
Hi, @e-z-t! Thank you for using our products. The btn-sm have intentionally the font-size a little higher than the regular one because like you will notice if you put the regular font-size on the btn-sm the text it will look so small and not clearly visible and with a text smaller than the regular in that case the text will not be visible at all. 

Second like you see in the image below the round button it's smaller than the others one and I used btn-sm with btn-round, so I don't understand where it's the problem here.
<img width="518" alt="screen shot 2018-09-06 at 10 14 00" src="https://user-images.githubusercontent.com/17456857/45141150-bb0e1e00-b1bd-11e8-9319-df1b18989576.png">

Yes, with the third issue you are right that menu button must be hidden when it's on mobile mode so here we must include this in the next update. That menu button must be only on the dashboard pages who have lateral menu not in the static pages without a sidebar. 

Regards,
Dragos

**Comment by ezehnder** [comment]
Hi @dragosct10, thank you for your feedback, much appreciated!

With regards to item 2., I made a mistake in my previous message: Seems that the issue with the button size appears when adding .btn-simple to a .btn-sm.btn-round (again, maybe this is by design, and not a bug, just thought it would be worth asking).

See, this is the code I have: 
```
<button class="btn btn-primary btn-sm btn-round">
    <i class="now-ui-icons ui-2_favourite-28"></i>
    Action A
</button>
<button class="btn btn-primary btn-sm btn-simple">
    <i class="now-ui-icons ui-2_favourite-28"></i>
    Action B
</button>
<button class="btn btn-primary btn-sm btn-simple btn-round">
    <i class="now-ui-icons ui-2_favourite-28"></i>
    Action C
</button>
```

This is how it looks like:
![image](https://user-images.githubusercontent.com/33011219/45154001-69a96300-b1ac-11e8-8509-26f7e7079f85.png)

where I would expect "Action C" to look like:
![image](https://user-images.githubusercontent.com/33011219/45154056-98bfd480-b1ac-11e8-908e-e82c1e1068d4.png)

it just seems a padding issue.

Thank you! Regards.

**Comment by dragosct** [comment]
Hi! Yes, you'are right this is an issue thank you very much for this observation. We will fix it and I will give the solution to you and also it will be included in the next update. Regards, Dragos

**Comment by dragosct** [comment]
To fix this issue please go in the scss/now-ui-dashboard/_buttons.scss and on line 162 you have these lines: 

```css
.btn-round{
    border-width: $border-thin;
    border-radius: $btn-round-radius;
    padding-right: $padding-round-horizontal;
    padding-left: $padding-round-horizontal;

    &.btn-simple {
        padding: $padding-btn-vertical - 1  $padding-round-horizontal - 1;
    }
}
```

and you have to put on the `.btn-simple` the next things: 

```css
.btn-round{
    border-width: $border-thin;
    border-radius: $btn-round-radius;
    padding-right: $padding-round-horizontal;
    padding-left: $padding-round-horizontal;

    &.btn-simple:not(.btn-sm):not(.btn-lg){
        padding: $padding-btn-vertical - 1  $padding-round-horizontal - 1;
    }
}
```

After that everything will work fine.

Regards, 
Dragos
